name: Deploy Front to S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choisir l’environnement'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync front-end to S3
        run: |
          aws s3 sync front-end/ s3://${{ github.event.inputs.environment }}.eksops.site --delete